### ISSUE TITLE
Works Really well after a few changes in my case

### ISSUE THREAD

**Issue by nslakshmiprabha** [LaTeX-Bibitem-Styler/latex-bibitemstyler#1]
Hi,

Thanks for sharing !!! Good job saved my time!!!

I am using Python 2.7.6, so had some problem but I fixed it.
Had this error
UnicodeEncodeError: 'ascii' codec can't encode characters in position 36-37: ordinal not in range(128)

fixed it by adding
reload(sys)
sys.setdefaultencoding("utf-8")

and there was one due to different python versions I guess
 with open(self.filePath + self.bibFilename, 'br') as f:
replaced it with 
 with open(self.filePath + self.bibFilename, 'r') as f:

and it worked like a charm!!!

Thanks once again!!!

**Comment by lukem512** [comment]
I've submitted a PR to fix this (see above reference). Hopefully the maintainer is still active and will merge this in.

**Comment by Andreea-G** [comment]
Thanks!!
